### ISSUE TITLE
Checkstyle validation parsing hangs in submit command

### ISSUE THREAD

**Issue by Salmela** [testmycode/tmc-core#110]
The problem seems to be that the SubmissionResultParser tries to [parse json](https://github.com/testmycode/tmc-core/blob/f1807c528e42eb2339efe8fbee80001e279a61f5/src/main/java/fi/helsinki/cs/tmc/core/communication/serialization/SubmissionResultParser.java#L43) with gson library, but the gson can't write the validationErrors map member in [ValidationResultImp](https://github.com/testmycode/tmc-core/blob/abab730b41f370df9ed6465bac6652929f02688e/src/main/java/fi/helsinki/cs/tmc/core/domain/submission/ValidationResultImpl.java#L14) .

The simplest way to fix this issue is just set the validationErrors member as transient. We tried it and it seemed to work. Another way that this could probably be fixed is set [validations member](https://github.com/testmycode/tmc-core/blob/95c449a3aac0baf477ffee29c05bf4aa701b858c/src/main/java/fi/helsinki/cs/tmc/core/domain/submission/SubmissionResult.java#L78) in SubmissionResult as transient.

This bug was discovered by @juvester .

**Comment by Salmela** [comment]
lol @juvester made exactly same issue #109 at almost the same time.

**Comment by juvester** [comment]
great minds think alike..
