### ISSUE TITLE
Investigate whether Exercise#{isReturnable, setReturnable} are used

### ISSUE THREAD

**Issue by nygrenh** [testmycode/tmc-core#114]

**Comment by jamo** [comment]
https://github.com/testmycode/tmc-netbeans/blob/core/tmc-plugin/src/fi/helsinki/cs/tmc/actions/AbstractExerciseSensitiveAction.java#L75

**Comment by nygrenh** [comment]
Strange, somehow ''Find usages' in Netbeans failed to find that.

**Comment by Rochet2** [comment]
Actually it seems tmc-core does not use either of them. Jamox's link is to some other repo.
And in that repo it seems setReturnable is not used even if isReturnable is used.

So things that use tmc-core use the functions?

**Comment by jamo** [comment]
the setter is either for gson deserialization or for testing (tho latter could be achieved just fine with mockito)

**Comment by nygrenh** [comment]
@Rochet2 No, I searched for both of the methods :).
