### ISSUE TITLE
Exercise downloader should use tmc-langs unzipper.

### ISSUE THREAD

**Issue by samutamm** [testmycode/tmc-core#14]

**Comment by samutamm** [comment]
Tmc-langs unzipping (and zipping) uses StudentFilePolicy-object to decide, which files should be zipped and unzipped. The logic for choosing correct StudentFilePolicy can be implemented to eiher tmc-core or tmc-langs. This decision should be made when tmc-langs-experts (Loezi/Jamo) come to work.

**Comment by zinkko** [comment]
a duplicate of this has been merged
