### ISSUE TITLE
Organisations to core

### ISSUE THREAD

**Issue by UMTti** [testmycode/tmc-core#16]
Core should have support to organisations

**Comment by josalmi** [comment]
Server doesn't currently support organization listing. Postponed for now

**Comment by jamo** [comment]
we really should define what org support really means.

In my opinion the biggest support feature would be the changes required for the directory structure.
e.g. currently: `course_name/exercise_name` => `org_name/course_name/exercise_name`
Not necessarily listing/selecting orgs.

Anyways we should define these soonish.

**Comment by jamo** [comment]
Nothing to do atm
