### ISSUE TITLE
Improve test coverage of tmc-core

### ISSUE THREAD

**Issue by UMTti** [testmycode/tmc-core#38]
At the moment it's 69%     https://coveralls.io/github/rage/tmc-core

**Comment by CorvusMathematicus** [comment]
I'd like to work on this one.

**Comment by jamo** [comment]
Awesome.
It might make sense not to make one huge PR improving all tests, but rather maybe do separate pull requests for each package or other nice chunk of code. Just to avoid any extra conflicts of simultaneous changes

**Comment by jamo** [comment]
Closing this for now.
