### ISSUE TITLE
If any client initiated action returns 404 re fetch courses.json and other files and try again with newly updated url.

### ISSUE THREAD

**Issue by jamo** [testmycode/tmc-core#39]
If any client initiated action returns 404 re fetch courses.json and other files and try again with newly updated url.

eg. when submit url address is changed

**Comment by ljleppan** [comment]
When a HTTP request sent to the server returns 404, the client should re-fetch any and all .json files. This is because one possible cause for the 404 is the server paths changing and the new JSON files would reflect this.

**Comment by UMTti** [comment]
Cache should be implemented
