### ISSUE TITLE
Parallelize exercise downloading

### ISSUE THREAD

**Issue by UMTti** [testmycode/tmc-core#47]
Now when user types tmc download <courseID>, all exercises will be downloaded in a single thread. When exercise amount is 100, it's stupid

**Comment by WaDelma** [comment]
I would like to work on this

**Comment by jamo** [comment]
I think we should make this somehow configurable by the caller -- also for the NetBeans UI I like the showing tasks individually; it shows a ton of tasks, each with separate progress bar.
So it's kinda unclear for me, whether this should be just called multiple times from the ui, or use similar status listener thingy as for submitting exercise and waiting for results

**Comment by jamo** [comment]
Irrelevant due to architectural changes
