### ISSUE TITLE
Refactor String path -> Path path

### ISSUE THREAD

**Issue by nygrenh** [testmycode/tmc-core#70]
Instead of strings for paths, we should prefer java.nio.file.Path.

**Comment by tieSari** [comment]
I could take this.
Sari R

**Comment by jamo** [comment]
You should be aware of the similar work at https://github.com/testmycode/tmc-netbeans/issues/111

**Comment by tieSari** [comment]
Ok!
Sari

**Comment by ljleppan** [comment]
NB: Prefer usage of `java.nio` instead of `java.io`.

That is, use `Files.exists(Path path)`\* instead of `path.toFile().exists()` etc. and preferably replace any existing usage of the class `File` with `Path`.

*) http://docs.oracle.com/javase/7/docs/api/java/nio/file/Files.html.
