### ISSUE TITLE
Get rid of Validations and ValidationErrors

### ISSUE THREAD

**Issue by nygrenh** [testmycode/tmc-core#71]
And use the correct interfaces from tmc-langs-abstraction.

**Comment by wakr** [comment]
Can work with this one, but more information could be nice :)

**Comment by ljleppan** [comment]
As far as I understand @nygrenh:

We want to replace [`fi.helsinki.cs.tmc.core.domain.submission.ValidationError`](https://github.com/testmycode/tmc-core/blob/master/src/main/java/fi/helsinki/cs/tmc/core/domain/submission/ValidationError.java) and [`fi.helsinki.cs.tmc.core.domain.submission.Validations`](https://github.com/testmycode/tmc-core/blob/master/src/main/java/fi/helsinki/cs/tmc/core/domain/submission/Validations.java) with the classes provided by [TMC-Langs-abstraction](https://github.com/testmycode/tmc-langs-abstraction).

**Comment by jamo** [comment]
Already done
