### ISSUE TITLE
Simplify and clean up test exercise resources

### ISSUE THREAD

**Issue by jamo** [testmycode/tmc-core#75]
We should try to reduce the amount of test resource exercises and make them more generic (rename references to our courses away)

However, keep in mind that there are some test resource exercises added for testing a specific bug.

**Comment by a544jh** [comment]
I could do this

**Comment by a544jh** [comment]
Is there anything that still could be done for this issue?

**Comment by jamo** [comment]
The test resources seems to be in really nice condition - one thing we still could do is to remove all references to existing exercises and finnish words. But I'm not sure whether it's worth it.
