### ISSUE TITLE
Don't manually attempt on generating urls but use provided ones

### ISSUE THREAD

**Issue by jamo** [testmycode/tmc-core#82]
We should get paths/urls from the json and not to generate it ourselfs.
(Only the courses.json needs to be defined manually.)
For all available courses we have the details url in the courses.json
https://github.com/testmycode/tmc-core/blob/master/src/main/java/fi/helsinki/cs/tmc/core/communication/UrlHelper.java#L31

**Comment by ghost** [comment]
I can fix this, are there other files where paths/urls from courses.json should be used instead?

**Comment by jamo** [comment]
Not sure, but in general we should never attempt to build urls, but use the one provided in courses.json and other json files linked from there. 
So that if we would change routing scheme of the server we wouldn't break anything

**Comment by jamo** [comment]
I feel like this is done as it's mostly rewritten
